package com.land.back.entities;

import java.util.Date;
import java.util.Map;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.land.back.jpa.tx.util.EntidadGenerica;
import com.land.back.util.Constantes;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "tb_usuario")
public class Usuario extends EntidadGenerica {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@SequenceGenerator(name = "seq_tb_usuario", sequenceName = "seq_tb_usuario", allocationSize = 1)
	@GeneratedValue(generator = "seq_tb_usuario", strategy = GenerationType.SEQUENCE)
	@Column(name = "id_usuario")
	private Long idUsuario = 0L;

	@Column(name = "clvusuario")
	private String usuario;

	@Column(name = "nombre")
	private String nombre;

	@Column(name = "paterno")
	private String paterno;

	@Column(name = "materno")
	private String materno;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "feccre")
	private Date feccre;

	@Column(name = "estatus")
	private Integer estatus;

	@Column(name = "contrasenia_sha")
	private byte[] contrasenia_sha;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reseteado")
	private Date reseteado;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo")
	private TipoUsuario tipoUsuario;

	@Column(name = "correo")
	private String correo;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_nacimiento")
	private Date fecha_nacimiento;

	@Transient
	private boolean reseteadoBole = false;

	@Transient
	private boolean estatusBole = true;

	public Usuario() {
	}

	public Usuario(Long id) {
		this.idUsuario = id;
	}

	public Long getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Long idUsuario) {
		this.idUsuario = idUsuario;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPaterno() {
		return this.paterno;
	}

	public void setPaterno(String paterno) {
		this.paterno = paterno;
	}

	public String getMaterno() {
		return this.materno;
	}

	public void setMaterno(String materno) {
		this.materno = materno;
	}

	public Integer getEstatus() {
		return estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

	@Transient
	public String getNombreCompleto() {
		return nombre + " " + paterno + " " + materno;
	}

	public void queryUsername() {
		this.queryHql = "FROM " + Usuario.class.getCanonicalName() + " u" + " WHERE u.clvusuario = :user";
		this.params.put("user", usuario);
	}
	
	public void queryEspecifico() {
		this.queryHql = "FROM " + Usuario.class.getCanonicalName() + " u" + " WHERE u.idUsuario = 1";
	}

	public void queryUsernamePasswordSha() {
		this.queryHql = "FROM " + Usuario.class.getCanonicalName() + " u"
				+ " WHERE u.usuario = :user AND u.contrasenia_sha = :pass AND u.estatus = :estatus";
		this.params.put("user", usuario);
		this.params.put("pass", contrasenia_sha);
		this.params.put("estatus", 1);
	}

	public void queryDelete() {
		this.queryHql = "FROM " + Usuario.class.getCanonicalName() + " u WHERE u.usuario = :user";
		this.params.put("user", usuario);
	}

	@Transient
	@Override
	public Object getId() {
		return idUsuario;
	}

	@Transient
	@Override
	public String getQueryHql() {
		return this.queryHql;
	}

	@Transient
	@Override
	public Map<Object, Object> getParametros() {
		return this.params;
	}

	public byte[] getContrasenia_sha() {
		return contrasenia_sha;
	}

	public void setContrasenia_sha(byte[] contrasenia_sha) {
		this.contrasenia_sha = contrasenia_sha;
	}

	public Date getReseteado() {
		return reseteado;
	}

	public void setReseteado(Date reseteado) {
		this.reseteado = reseteado;
	}

	@Override
	public <T extends EntidadGenerica> EntidadGenerica cloneObj(T obj) {
		Usuario actual = (Usuario) obj;
		nombre = actual.getNombre();
		paterno = actual.getPaterno();
		materno = actual.getMaterno();
		estatus = actual.getEstatus();
		contrasenia_sha = actual.getContrasenia_sha();
		reseteado = actual.getReseteado();
		fecha_nacimiento = actual.getFecha_nacimiento();
		correo = actual.getCorreo();
		tipoUsuario = actual.getTipoUsuario();
		return this;
	}

	public TipoUsuario getTipoUsuario() {
		return tipoUsuario;
	}

	public void setTipoUsuario(TipoUsuario tipoUsuario) {
		this.tipoUsuario = tipoUsuario;
	}

	@Transient
	public Integer getTempTipoUsuario() {
		if (tipoUsuario != null)
			return tipoUsuario.getIdTipoUsuario();
		else
			return 0;
	}

	public void setTempTipoUsuario(Integer tempTipoUsuario) {
		this.tipoUsuario = new TipoUsuario(tempTipoUsuario);
	}

	public String getCorreo() {
		return correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public void queryXCorreo() {
		this.queryHql = "FROM " + Usuario.class.getCanonicalName() + " u WHERE u.correo = :correo";
		this.params.put("correo", correo);
	}

	public void queryTipoUsuarioActivos() {
		this.queryHql = "FROM " + Usuario.class.getCanonicalName()
				+ " u WHERE u.id_tipo = :tipo AND u.estatus = :sta";
		this.params.put("tipo", tipoUsuario);
		this.params.put("sta", Constantes.ACTIVO);
	}

	public boolean isReseteadoBole() {
		return reseteadoBole;
	}

	public void setReseteadoBole(boolean reseteadoBole) {
		this.reseteadoBole = reseteadoBole;
	}

	public boolean isEstatusBole() {
		return estatusBole;
	}

	public void setEstatusBole(boolean estatusBole) {
		this.estatusBole = estatusBole;
	}

	public Date getFeccre() {
		return feccre;
	}

	public void setFeccre(Date feccre) {
		this.feccre = feccre;
	}

	public Date getFecha_nacimiento() {
		return fecha_nacimiento;
	}

	public void setFecha_nacimiento(Date fecha_nacimiento) {
		this.fecha_nacimiento = fecha_nacimiento;
	}

}
